// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAo12IBu178aMOJkLkLWjfuAI7TUoqgyYA',
    appId: '1:595245307645:web:766941f7fde1f9f3745094',
    messagingSenderId: '595245307645',
    projectId: 'fruit-market-app-4125c',
    authDomain: 'fruit-market-app-4125c.firebaseapp.com',
    storageBucket: 'fruit-market-app-4125c.appspot.com',
    measurementId: 'G-VLJP0DQGL3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIKbZCDUujVyeKtoXB-c0APjlwEjUUkz0',
    appId: '1:595245307645:android:d8f09f3a028b4547745094',
    messagingSenderId: '595245307645',
    projectId: 'fruit-market-app-4125c',
    storageBucket: 'fruit-market-app-4125c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiWqn2uYsVUjRXuMkgyzEg98K-iEmK_Mk',
    appId: '1:595245307645:ios:9e01152460d18b05745094',
    messagingSenderId: '595245307645',
    projectId: 'fruit-market-app-4125c',
    storageBucket: 'fruit-market-app-4125c.appspot.com',
    iosClientId: '595245307645-s8b2f43cfvds7kp7i1j1jtdhvg9gs4jr.apps.googleusercontent.com',
    iosBundleId: 'com.example.fruitMarketApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiWqn2uYsVUjRXuMkgyzEg98K-iEmK_Mk',
    appId: '1:595245307645:ios:9e01152460d18b05745094',
    messagingSenderId: '595245307645',
    projectId: 'fruit-market-app-4125c',
    storageBucket: 'fruit-market-app-4125c.appspot.com',
    iosClientId: '595245307645-s8b2f43cfvds7kp7i1j1jtdhvg9gs4jr.apps.googleusercontent.com',
    iosBundleId: 'com.example.fruitMarketApp',
  );
}
